version: '2'

services:
  blockbridge-storage-backend:
    image: blockbridge/simulator:swarm
    container_name: blockbridge-storage-backend
    networks:
      - storage
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "9999"
    ulimits:
      msgqueue: 128000000
    privileged: true
    entrypoint:
      - /bb/bin/startsim.sh
      - --container
      - --debug

networks:
  storage:
    driver: overlay
