version: '2'

services:
  voting-app:
    image: vieux/demo-vote
    ports:
      - "80"
    networks:
      - vote
    labels:
      com.docker.swarm.reschedule-policies: '["on-node-failure"]'

  result-app:
    image: vieux/demo-result
    ports:
      - "80"
    networks:
      - result
    labels:
      com.docker.swarm.reschedule-policies: '["on-node-failure"]'

  redis:
    image: redis:alpine
    networks:
      - vote
    labels:
      com.docker.swarm.reschedule-policies: '["on-node-failure"]'

  worker:
    image: vieux/demo-worker
    networks:
      - vote
    labels:
      com.docker.swarm.reschedule-policies: '["on-node-failure"]'

  db:
    image: postgres:9.4
    networks:
      - vote
      - result
      - storage
    volumes:
      - "db-data:/var/lib/postgresql/data"
    labels:
      com.docker.swarm.reschedule-policies: '["on-node-failure"]'
      com.docker.swarm.affinities: '["container==*blockbridge-volume-driver*"]'

volumes:
  db-data:
    driver: blockbridge

networks:
  vote:
    driver: overlay
  result:
    driver: overlay
  storage:
    driver: overlay
